export type InstallerInput = {
  orgId: string;
  orgName: string;
  firebaseProjectId: string;
  corsOrigin: string;
  runtimeVersion: string;
};

export function psQuote(value: string): string {
  return `'${String(value).replace(/'/g, "''")}'`;
}

export function installerFileName(orgName: string): string {
  const slug =
    (orgName || "cliente")
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^\w.-]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 40) || "cliente";
  return `Instalar-SEO-${slug}.ps1`;
}

export function defaultShellOrigin(origin: string): string {
  const trimmed = (origin || "").trim().replace(/\/$/, "");
  if (!trimmed) return "";
  try {
    const url = new URL(trimmed);
    if (url.protocol !== "https:") return "";
    if (/^(localhost|127\.0\.0\.1)$/i.test(url.hostname)) return "";
    return `${url.protocol}//${url.host}`;
  } catch {
    return "";
  }
}

export function assertInstallerInput(input: InstallerInput): void {
  if (!input.orgId.trim()) throw new Error("installer.missingOrg");
  if (!input.firebaseProjectId.trim()) throw new Error("installer.missingFirebase");
  if (!defaultShellOrigin(input.corsOrigin)) throw new Error("installer.corsHttps");
}

export function buildClientInstaller(input: InstallerInput): string {
  assertInstallerInput(input);
  const cors = defaultShellOrigin(input.corsOrigin);
  if (!cors) throw new Error("installer.corsHttps");
  const version = (input.runtimeVersion || "0.1.0").replace(/^v/i, "");
  const tag = `v${version}`;
  const zipTag = `https://github.com/beracoechea/SEO/archive/refs/tags/${tag}.zip`;
  const zipMain = "https://github.com/beracoechea/SEO/archive/refs/heads/main.zip";
  const releases = "https://api.github.com/repos/beracoechea/SEO/releases/latest";

  const lines = [
    "# Instalar / actualizar motor SEO en planta (generado desde /admin).",
    "# Click derecho > Ejecutar con PowerShell  O:",
    "#   powershell -ExecutionPolicy Bypass -File .\\" + installerFileName(input.orgName),
    "# Actualizacion silenciosa (no borra SQLite):",
    "#   powershell -ExecutionPolicy Bypass -File C:\\seo-runtime\\actualizar.ps1 -Mode Update",
    "# NUNCA uses: docker compose down -v   (eso borra el historial).",
    "param(",
    "  [ValidateSet('Install','Update')]",
    "  [string]$Mode = 'Install'",
    ")",
    "$ErrorActionPreference = 'Stop'",
    `$OrgId = ${psQuote(input.orgId.trim())}`,
    `$OrgName = ${psQuote(input.orgName.trim() || "cliente")}`,
    `$FirebaseProject = ${psQuote(input.firebaseProjectId.trim())}`,
    `$CorsOrigin = ${psQuote(cors)}`,
    `$RuntimeVersion = ${psQuote(version)}`,
    `$TagZip = ${psQuote(zipTag)}`,
    `$MainZip = ${psQuote(zipMain)}`,
    `$ReleasesUrl = ${psQuote(releases)}`,
    `$DockerSetup = ${psQuote("https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe")}`,
    "$InstallRoot = 'C:\\seo-runtime'",
    "$ComposeFile = Join-Path $InstallRoot 'deploy\\cliente\\docker-compose.yml'",
    "$EnvFile = Join-Path $InstallRoot 'deploy\\cliente\\.env'",
    "$VersionFile = Join-Path $InstallRoot 'VERSION.txt'",
    "$LogFile = Join-Path $InstallRoot 'update.log'",
    "$UpdaterFile = Join-Path $InstallRoot 'actualizar.ps1'",
    "$TaskName = 'Logicbus SEO runtime update'",
    "$ScriptPath = $MyInvocation.MyCommand.Path",
    "",
    "function Write-UpdateLog {",
    "  param([string]$Message)",
    "  $line = ('[{0}] {1}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message)",
    "  New-Item -ItemType Directory -Force -Path $InstallRoot | Out-Null",
    "  Add-Content -Path $LogFile -Value $line -Encoding UTF8",
    "  Write-Host $Message",
    "}",
    "",
    "function Refresh-Path {",
    "  $machine = [Environment]::GetEnvironmentVariable('Path','Machine')",
    "  $user = [Environment]::GetEnvironmentVariable('Path','User')",
    "  $env:Path = $machine + ';' + $user",
    "  $bin = 'C:\\Program Files\\Docker\\Docker\\resources\\bin'",
    "  if (Test-Path $bin) { $env:Path = $bin + ';' + $env:Path }",
    "}",
    "",
    "function Test-DockerReady {",
    "  Refresh-Path",
    "  if (-not (Get-Command docker -ErrorAction SilentlyContinue)) { return $false }",
    "  docker info 1>$null 2>$null",
    "  return ($LASTEXITCODE -eq 0)",
    "}",
    "",
    "function Wait-Docker {",
    "  param([int]$Tries = 60)",
    "  $wait = 0",
    "  while ($wait -lt $Tries) {",
    "    if (Test-DockerReady) { return $true }",
    "    Write-Host 'Esperando a que Docker Desktop quede Running...'",
    "    Start-Sleep -Seconds 5",
    "    $wait++",
    "  }",
    "  return $false",
    "}",
    "",
    "function Install-DockerDesktop {",
    "  Write-Host 'Docker no esta instalado. Se descarga Docker Desktop (oficial, ~500 MB)...'",
    "  $setup = Join-Path $env:TEMP 'DockerDesktopInstaller.exe'",
    "  Invoke-WebRequest -Uri $DockerSetup -OutFile $setup -UseBasicParsing",
    "  Write-Host 'Instalando Docker Desktop (silencioso)...'",
    "  $p = Start-Process -FilePath $setup -ArgumentList @('install','--quiet','--accept-license') -Wait -PassThru",
    "  $code = $p.ExitCode",
    "  Refresh-Path",
    "  $exe = 'C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe'",
    "  try { Add-LocalGroupMember -Group 'docker-users' -Member $env:USERNAME -ErrorAction SilentlyContinue } catch {}",
    "  if (Test-Path $exe) { Start-Process $exe }",
    "  if ($code -eq 3010) {",
    "    Write-Host 'Windows pide reiniciar para terminar Docker. Reinicia este PC y vuelve a ejecutar ESTE MISMO archivo .ps1'",
    "    if ($Mode -ne 'Update') { pause }",
    "    exit 0",
    "  }",
    "  if ($code -ne 0 -and -not (Test-Path $exe)) {",
    "    throw ('No se pudo instalar Docker Desktop (codigo ' + $code + '). Descarga https://www.docker.com/products/docker-desktop/ y reintenta este script.')",
    "  }",
    "}",
    "",
    "function Test-Admin {",
    "  $id = [Security.Principal.WindowsIdentity]::GetCurrent()",
    "  $p = New-Object Security.Principal.WindowsPrincipal($id)",
    "  return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)",
    "}",
    "",
    "function Read-EnvMap {",
    "  $map = @{}",
    "  if (Test-Path $EnvFile) {",
    "    Get-Content $EnvFile -ErrorAction SilentlyContinue | ForEach-Object {",
    "      if ($_ -match '^\\s*#' -or $_ -notmatch '=') { return }",
    "      $i = $_.IndexOf('=')",
    "      $k = $_.Substring(0, $i).Trim()",
    "      $v = $_.Substring($i + 1)",
    "      if ($k) { $map[$k] = $v }",
    "    }",
    "  }",
    "  return $map",
    "}",
    "",
    "function Write-RuntimeEnv {",
    "  param([switch]$KeepExtra)",
    "  $map = @{}",
    "  if ($KeepExtra) { $map = Read-EnvMap }",
    "  $map['ORG_ID'] = $OrgId",
    "  $map['FIREBASE_PROJECT_ID'] = $FirebaseProject",
    "  if (-not $map.ContainsKey('FIRESTORE_DATABASE')) { $map['FIRESTORE_DATABASE'] = 'webs' }",
    "  $map['CORS_ORIGIN'] = $CorsOrigin",
    "  if (-not $map.ContainsKey('RUNTIME_PORT')) { $map['RUNTIME_PORT'] = '8080' }",
    "  $map['RUNTIME_VERSION'] = $RuntimeVersion",
    "  New-Item -ItemType Directory -Force -Path (Split-Path $EnvFile) | Out-Null",
    "  $lines = @()",
    "  foreach ($k in @('ORG_ID','FIREBASE_PROJECT_ID','FIRESTORE_DATABASE','CORS_ORIGIN','RUNTIME_PORT','RUNTIME_VERSION')) {",
    "    $lines += ($k + '=' + $map[$k])",
    "    $map.Remove($k)",
    "  }",
    "  foreach ($k in ($map.Keys | Sort-Object)) {",
    "    $lines += ($k + '=' + $map[$k])",
    "  }",
    "  $lines | Set-Content -Path $EnvFile -Encoding ASCII",
    "}",
    "",
    "function Get-RuntimeHealth {",
    "  try {",
    "    return Invoke-RestMethod -Uri 'http://127.0.0.1:8080/api/health' -TimeoutSec 3",
    "  } catch {",
    "    return $null",
    "  }",
    "}",
    "",
    "function Test-CrawlBusy {",
    "  $h = Get-RuntimeHealth",
    "  if ($null -eq $h) { return $false }",
    "  return [bool]$h.busy",
    "}",
    "",
    "function Get-RemoteRuntime {",
    "  try {",
    "    $rel = Invoke-RestMethod -Uri $ReleasesUrl -TimeoutSec 20",
    "    if ($rel.tag_name) {",
    "      $ver = ([string]$rel.tag_name).TrimStart('v')",
    "      $zip = $rel.zipball_url",
    "      if (-not $zip) { $zip = ('https://github.com/beracoechea/SEO/archive/refs/tags/' + $rel.tag_name + '.zip') }",
    "      return @{ Version = $ver; Zip = $zip }",
    "    }",
    "  } catch {}",
    "  try {",
    "    Invoke-WebRequest -Uri $TagZip -Method Head -UseBasicParsing -TimeoutSec 15 | Out-Null",
    "    return @{ Version = $RuntimeVersion; Zip = $TagZip }",
    "  } catch {}",
    "  return @{ Version = 'main'; Zip = $MainZip }",
    "}",
    "",
    "function Install-RuntimeFiles {",
    "  param([string]$ZipUrl)",
    "  $tmpZip = Join-Path $env:TEMP 'seo-runtime-src.zip'",
    "  $unpack = Join-Path $env:TEMP 'seo-runtime-unpack'",
    "  if (Test-Path $unpack) { Remove-Item $unpack -Recurse -Force }",
    "  Write-UpdateLog 'Descargando el runtime...'",
    "  Invoke-WebRequest -Uri $ZipUrl -OutFile $tmpZip -UseBasicParsing",
    "  Expand-Archive -Path $tmpZip -DestinationPath $unpack -Force",
    "  $inner = Get-ChildItem $unpack | Select-Object -First 1",
    "  $envBackup = $null",
    "  if (Test-Path $EnvFile) { $envBackup = Get-Content $EnvFile -Raw }",
    "  New-Item -ItemType Directory -Force -Path $InstallRoot | Out-Null",
    "  Copy-Item -Path (Join-Path $inner.FullName '*') -Destination $InstallRoot -Recurse -Force",
    "  if ($envBackup) {",
    "    New-Item -ItemType Directory -Force -Path (Split-Path $EnvFile) | Out-Null",
    "    Set-Content -Path $EnvFile -Value $envBackup -Encoding ASCII",
    "  }",
    "}",
    "",
    "function Stop-RuntimeSafe {",
    "  if (-not (Test-Path $ComposeFile)) { return }",
    "  Write-UpdateLog 'Deteniendo el contenedor (se conserva el volumen runtime-data / SQLite)...'",
    "  Push-Location $InstallRoot",
    "  try {",
    "    docker compose -f $ComposeFile --env-file $EnvFile stop",
    "  } finally {",
    "    Pop-Location",
    "  }",
    "}",
    "",
    "function Start-Runtime {",
    "  Write-UpdateLog 'Levantando el motor (docker compose up -d --build; sin down -v)...'",
    "  Push-Location $InstallRoot",
    "  try {",
    "    docker compose -f $ComposeFile --env-file $EnvFile up -d --build",
    "    if ($LASTEXITCODE -ne 0) { throw 'docker compose fallo. Revisa que Docker Desktop este Running.' }",
    "  } finally {",
    "    Pop-Location",
    "  }",
    "}",
    "",
    "function Wait-RuntimeHealth {",
    "  param([int]$Tries = 30)",
    "  $health = $null",
    "  $wait = 0",
    "  while (-not $health -and $wait -lt $Tries) {",
    "    $health = Get-RuntimeHealth",
    "    if (-not $health) {",
    "      Start-Sleep -Seconds 2",
    "      $wait++",
    "    }",
    "  }",
    "  return $health",
    "}",
    "",
    "function Register-SilentUpdate {",
    "  try {",
    "    Copy-Item -Path $ScriptPath -Destination $UpdaterFile -Force",
    "    $args = '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File \"' + $UpdaterFile + '\" -Mode Update'",
    "    $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument $args",
    "    $daily = New-ScheduledTaskTrigger -Daily -At 3:20am",
    "    $logon = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME",
    "    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Hours 2)",
    "    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger @($daily, $logon) -Settings $settings -User $env:USERNAME -RunLevel Highest -Force | Out-Null",
    "    Write-UpdateLog ('Tarea programada: ' + $TaskName)",
    "  } catch {",
    "    Write-UpdateLog ('No se pudo registrar la actualizacion automatica: ' + $_.Exception.Message)",
    "  }",
    "}",
    "",
    "if (-not (Test-Admin)) {",
    "  if ($Mode -eq 'Update') {",
    "    Write-UpdateLog 'Actualizacion sin administrador; se intenta igual.'",
    "  } else {",
    "    Write-Host 'Se pide administrador para instalar Docker (si falta) y el firewall de la LAN.'",
    "    $here = $ScriptPath",
    "    Start-Process -FilePath powershell.exe -Verb RunAs -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File', $here, '-Mode', $Mode)",
    "    exit 0",
    "  }",
    "}",
    "",
    "Write-UpdateLog ('Logicbus SEO - ' + $Mode + ' para ' + $OrgName + ' ORG_ID ' + $OrgId)",
    "Refresh-Path",
    "",
    "if ($Mode -eq 'Update') {",
    "  if (-not (Test-DockerReady)) {",
    "    $exe = 'C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe'",
    "    if (Test-Path $exe) { Start-Process $exe }",
    "    if (-not (Wait-Docker -Tries 24)) {",
    "      Write-UpdateLog 'Docker Desktop no esta Running; se omite esta pasada.'",
    "      exit 0",
    "    }",
    "  }",
    "  if (Test-CrawlBusy) {",
    "    Write-UpdateLog 'Hay un escaneo en curso; no se actualiza para no cortar ni tocar SQLite. Se reintenta en la proxima pasada.'",
    "    exit 0",
    "  }",
    "  $remote = Get-RemoteRuntime",
    "  $local = ''",
    "  if (Test-Path $VersionFile) { $local = (Get-Content $VersionFile -Raw).Trim() }",
    "  if ($local -and $local -eq $remote.Version -and $remote.Version -ne 'main') {",
    "    Write-UpdateLog ('Ya esta en ' + $local + '; no hay tag nuevo.')",
    "    exit 0",
    "  }",
    "  Stop-RuntimeSafe",
    "  try {",
    "    Install-RuntimeFiles -ZipUrl $remote.Zip",
    "  } catch {",
    "    Write-UpdateLog ('Fallo la descarga; se vuelve a levantar el motor actual. ' + $_.Exception.Message)",
    "    if (Test-Path $ComposeFile) { Start-Runtime }",
    "    exit 1",
    "  }",
    "  Write-RuntimeEnv -KeepExtra",
    "  Start-Runtime",
    "  $health = Wait-RuntimeHealth",
    "  if (-not $health) {",
    "    Write-UpdateLog 'El motor no respondio tras actualizar.'",
    "    exit 1",
    "  }",
    "  Set-Content -Path $VersionFile -Value $remote.Version -Encoding ASCII",
    "  try { Copy-Item -Path $ScriptPath -Destination $UpdaterFile -Force } catch {}",
    "  Write-UpdateLog ('Actualizado a ' + $remote.Version + '. Volumen runtime-data intacto.')",
    "  exit 0",
    "}",
    "",
    "if (-not (Test-DockerReady)) {",
    "  $exe = 'C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe'",
    "  if (Test-Path $exe) { Start-Process $exe } else { Install-DockerDesktop }",
    "}",
    "if (-not (Wait-Docker)) {",
    "  $exe = 'C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe'",
    "  if (Test-Path $exe) { Start-Process $exe }",
    "  if (-not (Wait-Docker -Tries 24)) {",
    "    throw 'Docker Desktop no quedo Running. Si Windows pidio reinicio, reinicia y vuelve a ejecutar este mismo .ps1'",
    "  }",
    "}",
    "",
    "New-Item -ItemType Directory -Force -Path $InstallRoot | Out-Null",
    "if (-not (Test-Path $ComposeFile)) {",
    "  $remote = Get-RemoteRuntime",
    "  try {",
    "    Install-RuntimeFiles -ZipUrl $remote.Zip",
    "  } catch {",
    "    Write-Host 'No hubo tag; se usa main.'",
    "    Install-RuntimeFiles -ZipUrl $MainZip",
    "    $remote = @{ Version = 'main'; Zip = $MainZip }",
    "  }",
    "  Set-Content -Path $VersionFile -Value $remote.Version -Encoding ASCII",
    "}",
    "",
    "Write-RuntimeEnv -KeepExtra",
    "Start-Runtime",
    "",
    "if (Test-Admin) {",
    "  netsh advfirewall firewall delete rule name='SEO runtime LAN' 1>$null 2>$null",
    "  netsh advfirewall firewall add rule name='SEO runtime LAN' dir=in action=allow protocol=TCP localport=8080 profile=private | Out-Null",
    "}",
    "",
    "$health = Wait-RuntimeHealth",
    "if (-not $health) { throw 'El motor no respondio en http://127.0.0.1:8080/api/health' }",
    "Register-SilentUpdate",
    "",
    "$ips = @(Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object {",
    "  $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*'",
    "} | Select-Object -ExpandProperty IPAddress)",
    "Write-Host ''",
    "Write-Host 'Listo. En ESTE PC: http://127.0.0.1:8080/api/health'",
    "if ($ips.Count -gt 0) {",
    "  Write-Host 'En la oficina usa (misma LAN):'",
    "  $ips | ForEach-Object { Write-Host ('  http://' + $_ + ':8080') }",
    "  Write-Host 'Copia esa URL en /admin de la org, campo motor LAN.'",
    "}",
    "Write-Host ($health | ConvertTo-Json -Compress)",
    "Write-Host ''",
    "Write-Host 'El motor se actualiza solo (tarea diaria 03:20 y al iniciar sesion). No expongas el 8080 a internet.'",
    "pause",
  ];
  return lines.join("\r\n") + "\r\n";
}

export const INSTALLER_RUNTIME_VERSION = "0.1.0";

export function downloadClientInstaller(input: InstallerInput) {
  const body = buildClientInstaller(input);
  const bom = new Uint8Array([0xef, 0xbb, 0xbf]);
  const bytes = new TextEncoder().encode(body);
  const blob = new Blob([bom, bytes], { type: "text/plain;charset=utf-8" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = installerFileName(input.orgName);
  link.click();
  URL.revokeObjectURL(link.href);
}
